# Theme Settings
title: Sara Kamdod

logo: "/SARA.png"
description: >
  <br>
  Junior Data/AI software Developer
  <br>
  <br>
  Contact me at: 7338338760
  <br>
  <a href="https://www.linkedin.com/in/sara-kamdod-1123591a6">
    <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?&style=for-the-badge&logo=linkedin&logoColor=white">
  </a>
  <a href="sarakamdod04@gmail.com">
    <img alt="Gmail" src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" />
  </a>
theme: jekyll-theme-minimal
